### PR TITLE
Add database test data + Unit test scaffolding

### PR DESCRIPTION
**Pull request by Dillon-Brown**
Running locally: ```docker build .```

### CODE REVIEW

**Comment by Amckenzie93** [comment]
Code changes approved, although i noticed travis CI appears to have thrown a build failure on each update in this PR - is this ok to merge?

**Comment by Dillon-Brown** [comment]
@Amckenzie93 Do you mean the build errors in the older commits? those can be ignored as each new commit triggers a new Travis build superseding the old ones.

**Comment by Dillon-Brown** [comment]
And yeah this is good to merge if everyone is happy with the code.

**Comment by Amckenzie93** [comment]
Think its just my misunderstanding of the comment messages above regarding each commit, as there are two whole comments 9 days ago and each contain one red cross. but if its good to go then im happy 👍

**Comment by Dillon-Brown** [comment]
@Amckenzie93 Easiest way to check if a PR is passing is to expand the "Show all checks" at the bottom and then clicking on details to get to the Travis build. That one will always be the most recent build.

**Pull request merged**
